### ISSUE TITLE
got an error when specifically using this mod not sure what's wrong with it but here is the crash report if you could help me know what's causing this ! thank you for your time

### ISSUE THREAD

**Issue by niseiow** [Ineffa/Wondrous-Wilds#2]
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 7/8/22, 8:55 PM
Description: mouseClicked event handler

com.google.gson.JsonParseException: Error loading registry data: Unknown element: ResourceKey[minecraft:worldgen/configured_feature / wondrouswilds:fancy_birch]; Unknown element: ResourceKey[minecraft:worldgen/configured_feature / wondrouswilds:fancy_birch_with_bees]
	at net.minecraft.class_5455.method_34849(class_5455.java:298)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at net.minecraft.class_5455.method_30526(class_5455.java:298)
	at net.minecraft.class_5455.method_30519(class_5455.java:292)
	at net.minecraft.class_6903.method_40413(class_6903.java:32)
	at net.minecraft.class_5455.method_40314(class_5455.java:269)
	at net.minecraft.class_525.method_41854(class_525.java:147)
	at net.minecraft.class_525.md68a38f$lambda$bcl_NewDefaultSettings$0$0(class_525.java:777)
	at net.minecraft.class_7237.method_42098(class_7237.java:24)
	at net.minecraft.class_525.method_31130(class_525.java:144)
	at net.minecraft.class_526.method_19944(class_526.java:72)
	at net.minecraft.class_4185.method_25306(class_4185.java:40)
	at net.minecraft.class_4264.method_25348(class_4264.java:16)
	at net.minecraft.class_339.method_25402(class_339.java:120)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_312.method_1611(class_312.java:94)
	at net.minecraft.class_437.method_25412(class_437.java:491)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:222)
	at net.minecraft.class_310.method_1523(class_310.java:1174)
	at net.minecraft.class_310.method_1514(class_310.java:734)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_5455.method_34849(class_5455.java:298)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at net.minecraft.class_5455.method_30526(class_5455.java:298)
	at net.minecraft.class_5455.method_30519(class_5455.java:292)
	at net.minecraft.class_6903.method_40413(class_6903.java:32)
	at net.minecraft.class_5455.method_40314(class_5455.java:269)
	at net.minecraft.class_525.method_41854(class_525.java:147)
	at net.minecraft.class_525.md68a38f$lambda$bcl_NewDefaultSettings$0$0(class_525.java:777)
	at net.minecraft.class_7237.method_42098(class_7237.java:24)
	at net.minecraft.class_525.method_31130(class_525.java:144)
	at net.minecraft.class_526.method_19944(class_526.java:72)
	at net.minecraft.class_4185.method_25306(class_4185.java:40)
	at net.minecraft.class_4264.method_25348(class_4264.java:16)
	at net.minecraft.class_339.method_25402(class_339.java:120)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_312.method_1611(class_312.java:94)
	at net.minecraft.class_437.method_25412(class_437.java:491)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)

-- Affected screen --
Details:
	Screen name: net.minecraft.class_526
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:491)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:222)
	at net.minecraft.class_310.method_1523(class_310.java:1174)
	at net.minecraft.class_310.method_1514(class_310.java:734)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Mizunos-16-Craft-Resource-Pack-1.19.zip, Unity-1.19.X-Dark-0.8.1.zip, Fabric Mods
Stacktrace:
	at net.minecraft.class_6360.method_36565(class_6360.java:49)
	at net.minecraft.class_310.method_1587(class_310.java:2295)
	at net.minecraft.class_310.method_1514(class_310.java:753)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 2390751232 bytes (2279 MiB) / 4529848320 bytes (4320 MiB) up to 17951621120 bytes (17120 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 13
	Microarchitecture: unknown
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GTX 1070
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1b81
	Graphics card #0 versionInfo: DriverVersion=30.0.15.1295
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 37554.67
	Virtual memory used (MB): 25324.33
	Swap memory total (MB): 4864.00
	Swap memory used (MB): 289.92
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx17120m -Xms256m
	Fabric Mods: 
		additionaladditions: Additional Additions 5.0.1
			libgui: LibGui 6.0.0-beta.5+1.19-pre1
				jankson: Jankson 4.1.1+j1.2.1
					blue_endless_jankson: jankson 1.2.1
				libninepatch: LibNinePatch 1.1.0
		additionalstructures: Additional Structures 4.0.0
		advancednetherite: Advanced Netherite 1.6.0-1.19
		advancementplaques: Advancement Plaques 1.4.5
		adventurez: AdventureZ 1.4.14
		amethystequipment: Amethyst Equipment 1.0.3
		animal_origins_18: Animal Origins 1.0.0
		appleskin: AppleSkin 2.4.0+mc1.19
		aqupdcaracal: Caracal mob 1.19-1.3.9
		aqupdgrizzly: Grizzly Bear mob 1.19-1.3
		architects_palette: Architect's Palette Fabric 2.1.1
		architectury: Architectury 5.7.28
		armor_visibility: Armor Visibility 5.0.1
		attributefix: AttributeFix 15.0.1
		auudio: Auudio 1.0.3
		awesomedungeon: Awesome Dungeon 2.0.10
		awesomedungeonend: Awesome Dungeon Edition end 1.0.2
		awesomedungeonnether: Awesome Dungeon Edition Nether 1.0.2
		awesomedungeonocean: Awesome Dungeon Edition Ocean 2.0.7
		backslot: BackSlot 1.2.8
			amecsapi: Amecs API 1.3.6+mc22w17a
		badpackets: Bad Packets 0.1.2
		bclib: BCLib 2.0.5
		betteranimalsplus: Better Animals Plus 1.19-11.0.6
		betterend: Better End 2.0.2
		betterf3: BetterF3 1.3.1
		betternether: Better Nether 7.0.2
		betterthirdperson: Better Third Person 1.8.1
		blockus: Blockus 2.5.0+1.19-rc2
			terraform-wood-api-v1: Terraform Wood API (v1) 4.0.0-alpha.4
		blossom: Blossom 1.0.5
		blur: Blur (Fabric) 2.6.0
			satin: Satin 1.8.0
		boatcontainer: BoatContainer 1.1.0
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.4.1-1.19
			maelstrom_library: Maelstrom Library 1.3-1.19-pre1
			multipart_entities: MultipartEntities 1.2-1.19-pre1
		byg: Oh The Biomes You'll Go 2.0.0.5
		capybara: Capybara 1.0.5
		cardinal-components: Cardinal Components API 5.0.0-beta.1
			cardinal-components-base: Cardinal Components API (base) 5.0.0-beta.1
			cardinal-components-block: Cardinal Components API (blocks) 5.0.0-beta.1
			cardinal-components-chunk: Cardinal Components API (chunks) 5.0.0-beta.1
			cardinal-components-entity: Cardinal Components API (entities) 5.0.0-beta.1
			cardinal-components-item: Cardinal Components API (items) 5.0.0-beta.1
			cardinal-components-level: Cardinal Components API (world saves) 5.0.0-beta.1
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.0.0-beta.1
			cardinal-components-world: Cardinal Components API (worlds) 5.0.0-beta.1
		castle_dungeons: Castle Dungeons 3.3-1.19-fabric
		chat_heads: Chat Heads 0.6.0
		cleancut: CleanCut 1.19-5.0-fabric
		clear-skies: Clear Skies 2.0.94
		cloth-config: Cloth Config v6 7.0.72
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 9.0.0+3
		collective-fabric: Collective (Fabric) 4.27
			fiber: fiber 0.23.0-2
		coloredglowlib: ColoredGlow Lib 1.3.4
		controlling: Controlling For Fabric 10.0+1
		coppergolem: YDM's Copper Golem 2.0.0
		cotw: Curse Of The Warden 1.0.0
		creativecore: CreativeCore (Fabric) 2.7.2
		cryingghasts-fabric: Crying Ghasts (Fabric) 1.6
		dark-loading-screen: Dark Loading Screen 1.6.12
		darkness: True Darkness 2.0.94
		deepslatecutting: Deepslate Cutting 1.4.0
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
			maybe-data: Maybe data 1.3.1-1.18.2
		dehydration: Dehydration 1.2.9
		disenchanter: Disenchanter 0.1.7+1.19
		doggomod: Doggo Mod 1.2.0
		doom: Doom Fabric 4.2.5
		doubledoors-fabric: Double Doors (Fabric) 3.4
		dragonloot: DragonLoot 1.1.1
		drippyloadingscreen: Drippy Loading Screen 1.6.4
		duckling: Duckling 2.0.3
		dungeons_arise: When Dungeons Arise 2.1.51
		durabilityviewer: Giselbaers Durability Viewer 1.19-fabric0.53.3-1.10.3
			crowdin-translate: CrowdinTranslate 1.4+1.19
			gbfabrictools: GBfabrictools 1.3.4+1.19
		dwayne-the-block-johnson: Dwayne 'The Block' Johnson 2.1.0
		dynamicsoundfilters: Dynamic Sound Filters 1.3.0+1.19
		earthtojavamobs: Earth2Java 1.9.1
		ecologics: Ecologics 2.1.1
		edenring: EdenRing 0.6.3
		effective: Effective 1.2.2
		emerald_tools: Emerald Tools 1.4.14
			pugh_tools: Pugh Tools 1.3.10
		enderitemod: Enderite Mod 1.4.1
		endrem: End Remastered 5.1.0
		enhancedcelestials: Enhanced Celestials 2.0.0.0
		enhancedvisuals: Enhanced Visuals (Fabric) 1.5.6
		entity_texture_features: Entity Texture Features 3.1.4
		environmentz: EnvironmentZ 1.2.3
		equipmentcompare: Equipment Compare 1.3.1
		exlineawnings: Exline's Awnings Mod 1.1.0
		exlinecopperequipment: Copper Equipment 2.0.3
		extraorigins: Extra Origins 1.19-1
		fabric: Fabric API 0.57.0+1.19
			fabric-api-base: Fabric API Base 0.4.9+e62f51a3a9
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.7+9ff28f40a9
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.14+b2a4a624a9
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.18+9ff28f40a9
			fabric-command-api-v1: Fabric Command API (v1) 1.2.6+f71b366fa9
			fabric-command-api-v2: Fabric Command API (v2) 2.1.2+0d55f585a9
			fabric-commands-v0: Fabric Commands (v0) 0.2.23+df3654b3a9
			fabric-containers-v0: Fabric Containers (v0) 0.1.27+df3654b3a9
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.2.0+07df213ea9
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.8+37622d24a9
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.3+bd0a0d4aa9
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.1.1+a680b9b4a9
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.28+a6d2f785a9
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.16+9ff28f40a9
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.26+9ff28f40a9
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.25+df3654b3a9
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.19+18990361a9
			fabric-item-api-v1: Fabric Item API (v1) 1.5.4+767db26ea9
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.25+9ff28f40a9
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.18+9ff28f40a9
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.16+df3654b3a9
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+33fbc738a9
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.0+03a4e568a9
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.3+9e7660c6a9
			fabric-message-api-v1: Fabric Message API (v1) 1.0.1+513f4a59a9
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.10+33fbc738a9
			fabric-models-v0: Fabric Models (v0) 0.3.15+9ff28f40a9
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.27+7fe97409a9
			fabric-networking-v0: Fabric Networking (v0) 0.3.14+df3654b3a9
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.7+9ff28f40a9
			fabric-particles-v1: Fabric Particles (v1) 1.0.8+dc39553aa9
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.17+23c4cfefa9
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.8+9ff28f40a9
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.9+1f92344ea9
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.18+df3654b3a9
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.12+9ff28f40a9
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.5+9ff28f40a9
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.20+df3654b3a9
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.14+9ff28f40a9
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.9+e62f51a3a9
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.5+a6d2f785a9
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.24+f05effafa9
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.6+9ff28f40a9
			fabric-textures-v0: Fabric Textures (v0) 1.0.18+9ff28f40a9
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.0.9+e62f51a3a9
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.1+9e7660c6a9
		fabric-language-kotlin: Fabric Language Kotlin 1.7.4+kotlin.1.6.21
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.6.21
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.6.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.6.21
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.1
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.1
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.2
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.2
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.2
		fabricloader: Fabric Loader 0.14.6
		fallingleaves: Falling Leaves 1.12.1+1.19
		fallingtree: FallingTree 3.6.3
		firstperson: FirstpersonModel 2.1.0
		forgeconfigapiport: Forge Config API Port 4.0.0
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
		foxglow: FoxGlow 1.3.0
		friendsandfoes: Friends&Foes 1.5.4
			mm: Manningham Mills 2.3
		fwaystones: Fabric Waystones 3.0.1+mc1.19
		geckolib3: Geckolib 3.1.5
			com_eliotlash_mclib_mclib: mclib 18
			com_eliotlash_molang_molang: molang 18
		giantspawn-fabric: Giant Spawn (Fabric) 2.9
		gobber2: Gobber2 2.6.18
			pugh_lib: Pugh Lib 1.4.8
		graveyard: The Graveyard 1.10
			omega-config: OmegaConfig 1.2.2-1.18.1
		graveyard_biomes: The Graveyard Biomes 1.2
		greater_eye: Greater Eye of Ender 1.4.12
		grounded_origins: Grounded Origins 1.2.1
			apugli: Apugli 1.7.2
				com_github_llamalad7_mixinextras: MixinExtras 0.0.10
		harvest_scythes: Harvest Scythes 2.5.2
		healingcampfire-fabric: Healing Campfire (Fabric) 3.5
		highlighter: Highlighter 1.1.2
		huskspawn-fabric: Husk Spawn (Fabric) 1.6
		ibarnorigins: ibarn's origins addon 1.1.1
		iceberg: Iceberg 1.0.38
		illuminations: Illuminations 1.10.8
		immortuoscalyx: Immortuos Calyx 1.7.2
		impaled: Impaled 1.1.4
		incendium: Incendium + Seed Fix 5.1.0
		infusion_table: Infusion Table 1.1.0
		iris: Iris 1.2.5
			org_anarres_jcpp: jcpp 1.4.14
		itemborders: Item Borders 1.1.6
		jade: Jade 7.3.1
		jamlib: JamLib 0.1.0
		java: OpenJDK 64-Bit Server VM 17
		konkrete: Konkrete 1.3.3
		lambdynlights: LambDynamicLights 2.1.2+1.19
			pride: Pride Lib 1.1.2+1.19
			spruceui: SpruceUI 4.0.0+1.19
		lazydfu: LazyDFU 0.1.3
		legendarytooltips: Legendary Tooltips 1.2.6
		libraryferret: Library Ferret 1.0.3
		mavm: More Axolotl Variants Mod 1.0.8a
		mcda: MC Dungeons Armors 2.1.0
		mcdar: MC Dungeons Artifacts 1.5.0
		mcdw: MC Dungeons Weapons 4.4.0-1.19
			enchant_giver: Enchant Giver 1.3.0
			reach-entity-attributes: Reach Entity Attributes 2.3.0
		mcwroofs: Macaw's Roofs 2.1.2
		medievalentity: Mediaval Entity 2.0.1
		medievalmusic: Medieval Music Mod 1.19-1.8
		medievalorigins: Medieval Origins 1.19.x-4.1.1
		megaparrot: Megaparrot 1.0.5
		midnightlib: MidnightLib 0.5.2
		minecraft: Minecraft 1.19
		mo_glass: Mo Glass 1.6.1-MC1.19
		moborigins: Mob Origins 1.9.0
		mobs_attempt_parkour: Mobs Attempt Parkour 0.3-1.19-pre1
		modid: Creatures Of The Snow 2.2.0+1.19
		modmenu: Mod Menu 4.0.0
		more-axolotls: More Axolotls 1.0.2
		more_babies: More Babies 0.5.2
		morebannerfeatures: More Banner Features 1.1.3
		morevillagers: More Villagers 4.0.2
		mousetweaks: Mouse Tweaks 2.22
		mtmechs: Magitek Mechs 1.0.14
			team_reborn_energy: Energy 2.0.0-beta1
		musicdr: Music Duration Reducer 2.1.0
		mypack: My Pack 1.0.0
		namepain: Name Pain 1.4.0
		naturallychargedcreepers-fabric: Naturally Charged Creepers (Fabric) 1.9
		nears: Nears 1.2.0
		notenoughanimations: NotEnoughAnimations 1.6.0
		nyfsquiver: Nyf's Quivers Fabric-0.5.0-1.19-rc2
		observed: Observed 1.3.2
		obsidianequipment: Obsidian Equipment 1.0.2
		onsoulfire: On Soul Fire 1.19-2
		origins: Origins 1.6.1
			apoli: Apoli 2.5.0
				additionalentityattributes: Additionalentityattributes 1.0.0+1.19
				calio: Calio 1.7.0
				playerabilitylib: Pal 1.6.0
		origins-classes: Origins: Classes 1.4.0
		overweight_farming: Overweight Farming 1.19-1.5.0-fabric
		owo: oωo 0.7.3+1.19
		oxidized: Oxidized 1.7.0
		passiveendermen-fabric: Passive Endermen (Fabric) 2.4
		pehkui: Pehkui 3.3.3+1.14.4-1.19.1
			kanos_config: Kanos Config 0.3.1+1.14.4-1.19
		physicsmod: Physics Mod 2.8.1
		presencefootsteps: Presence Footsteps 1.6.1
			kirin: Kirin UI 1.11.0
		raised: Raised 1.1.2
		reeses-sodium-options: Reese's Sodium Options 1.4.3+mc1.19-build.43
		rightclickharvest: Right Click Harvest 2.2.0
		roughlyenoughitems: Roughly Enough Items 9.0.493
		sculksieg: TheSculker 5.5 1.19 1.0.0
		sheepsqueak: Sheep Squeak 1.0.1
		simple_backpack: SimpleBackpack 1.3.16
		simply_houses: Simply Houses 1.1.3-1.19
		sit: Sit 1.19-20
		skeletonhorsespawn-fabric: Skeleton Horse Spawn (Fabric) 2.1
		skinlayers: 3d Skin Layers 1.4.7-mc1.19
		sleepwarp: SleepWarp 1.2.0+1.19
		snowballsfreezemobs-fabric: Snowballs Freeze Mobs (Fabric) 1.7
		sodium: Sodium 0.4.2+build.16
			org_joml_joml: joml 1.10.4
		sodium-extra: Sodium Extra 0.4.5+mc1.19-build.43
			caffeineconfig: CaffeineConfig 1.0.0+1.17
		stoneholm: Stoneholm 1.4.4
		strawgolem: Straw Golem 2.0.0b1
		strayspawn-fabric: Stray Spawn (Fabric) 1.7
		structory: Structory 1.0.1
		styled-nicknames: Styled Nicknames 1.1.0+1.19
			player-data-api: Player Data API 0.1.0+1.18
		styledplayerlist: Styled Player List 2.2.1+1.19
		t_and_t: Towns and Towers - Structure Add-on 1.7
		terrablender: TerraBlender 2.0.0.112
		terralith: Terralith 2.3
		the_bumblezone: The Bumblezone - Fabric 6.0.1+1.19
			fake-player-api: Fake Player API 0.3.0
		things: Things 0.2.19+1.19
		tooltipfix: ToolTip Fix 1.0.5-1.19
		torohealth: ToroHealth Damage Indicators 1.19-fabric-1
		totw_additions: Towers of the Wild: Additions 1.2.3
		transportables: Transportables 1.2.1
		trinkets: Trinkets 3.4.0
		universal-graves: Universal Graves 2.1.0+1.19
			common-protection-api: Common Protection API 1.0.0
			fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
			hologram-api: Hologram API 0.2.2+1.19
			placeholder-api: Placeholder API 2.0.0-beta.6+1.19
			polymer: Polymer (Core) 0.2.2+1.19
				polymer-registry-sync-manipulator: Polymer Registry Sync Manipulator 0.0.1+1.19
			server_translations_api: Server Translations API 1.4.16+1.19
				packet_tweaker: Packet Tweaker 0.3.0+1.18.2
			sgui: sgui 1.1.1+1.19
		victus: Victus 0.1.11+1.19
		villagernames-fabric: Villager Names (Fabric) 3.6
		visuality: Visuality 0.5.0
		voidz: VoidZ 1.0.8
		warhammersmod: War-Hammers Mod 1.0.2
		whisperwoods: Whisperwoods 1.19-2.1.0
		wondrouswilds: Wondrous Wilds 1.19-1.0.1
		woodarmor: Wooden Armors (+ Stone Armor) 1.0.2
		xaerominimap: Xaero's Minimap 22.9.3
		xaeroworldmap: Xaero's World Map 1.24.0
		xps: Xp Obelisk 0.4.1.r_for_1.19.x_Fabric
		zombiehorsespawn-fabric: Zombie Horse Spawn (Fabric) 3.1
	Loaded Shaderpack: Insanity-Shader-Universal-v1.231 (1).zip
		Profile: ULTRA (+4 options changed by user)
	Launched Version: fabric-loader-0.14.6-1.19
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce GTX 1070/PCIe/SSE2 GL version 3.2.0 NVIDIA 512.95, NVIDIA Corporation
	Window size: 1024x768
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, file/Mizunos-16-Craft-Resource-Pack-1.19.zip, file/Unity-1.19.X-Dark-0.8.1.zip, Fabric Mods
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz

**Comment by NeffaDev** [comment]
This is a strange issue, because this crash seems to have been caused by some of the world features from this mod not registering correctly. I would think that maybe this is somehow a compatibility issue, but I'm not sure what mod could possibly be interfering with such a thing, so if that is the case then I wouldn't have any idea what mod it is to be honest.

Can you try messing around with your mod list and see if it still persists? Like, removing some mods to try and narrow it down a bit, and maybe try using the mod by itself as well? (with dependencies of course)
