### ISSUE TITLE
Config option to turn off the shader compatibility warning

### ISSUE THREAD

**Issue by Defetyre** [Ineffa/Wondrous-Wilds#7]
Hello, I'm using your mod with iris-mc1.19.2-1.3.1 along with Complementary v4.6 (compatibility mode is set to off) and around other 150 mods including various intrusive optimization mods and other mods that use Geckolib(3.1.19). 
I never found any issues with animations when shaders are on, and everything seems to work as intended, and yet your mod shows warning on every word start up that tells me otherwise. Please consider checking if this warning is still relevant and remove it or add such option in config if the issue only triggers with specific shaders

**Comment by NeffaDev** [comment]
This option already exists in the config as of version 1.1.2
